[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python -m gunicorn --bind 0.0.0.0:$PORT web_app:app"